name       : byobu
version    : '5.116'
release    : 2
source     :
    - https://launchpad.net/byobu/trunk/5.116/+download/byobu_5.116.orig.tar.gz : 85251e149bc56cfeb299c88b32390889b73b444f47039f9206a012602ecb9748
license    : GPL-3.0
component  : system.utils
summary    : Byobu is an enhancement for the GNU Screen or Tmux
description: |
    Byobu includes an enhanced profile, configuration utilities, and system status notifications for the GNU screen window manager as well as the Tmux terminal multiplexer.
rundeps    :
    - tmux
    - newt
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
